import Head from 'next/head';

import Layout from '../components/layouts/Layout';
import { useLocale } from '../hooks/useLocale';

import type { NextPage } from 'next';

const ENV = process.env.NEXT_PUBLIC_ENV;

const Home: NextPage = () => {
  const { t } = useLocale();

  console.log('stage =', ENV);

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <p className="text-xl">{t('home/greet')}</p>
      </div>
    </Layout>
  );
};

export default Home;
