import Head from 'next/head';

import Layout from '../components/layouts/Layout';
import { useLocale } from '../hooks/useLocale';

import type { NextPageWithLayout } from 'next';

const Home: NextPageWithLayout = () => {
  const { t } = useLocale();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="grow px-6 py-2">
        <div className="container mx-auto">
          <div className="text-xl">{t.MAIN_CONTENT}</div>
        </div>
      </main>
    </>
  );
};

Home.getLayout = page => <Layout>{page}</Layout>;

export default Home;
