import Head from 'next/head';

import Layout from '../components/layouts/Layout';
import { useLocale } from '../hooks/useLocale';

import type { NextPage } from 'next';

const Home: NextPage = () => {
  const { t } = useLocale();

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="grow px-6 py-2">
        <div className="container mx-auto">
          <div className="text-xl">{t('home/greet')}</div>
        </div>
      </main>
    </Layout>
  );
};

export default Home;
