import { ConnectButton } from '@rainbow-me/rainbowkit';
import { unstable_getServerSession } from 'next-auth';
import Head from 'next/head';

import Layout from '../components/layouts/Layout';
import { getAuthOptions } from './api/auth/[...nextauth]';

import type { GetServerSideProps, NextPage } from 'next';

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  return {
    props: {
      session: await unstable_getServerSession(req, res, getAuthOptions(req)),
    },
  };
};

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main
        style={{
          height: '100vh',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          gap: 32,
        }}
      >
        <ConnectButton />
        <ConnectButton chainStatus="name" />
        <ConnectButton chainStatus="icon" />
        <ConnectButton chainStatus="none" />
        <ConnectButton accountStatus="avatar" />
        <ConnectButton accountStatus="address" />
        <ConnectButton showBalance={true} />
        <ConnectButton showBalance={false} />
        <ConnectButton label="Hello" />
      </main>{' '}
    </Layout>
  );
};

export default Home;
